# Generated by Django 5.2.5 on 2025-08-22 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='late_days',
        ),
        migrations.AddField(
            model_name='performance',
            name='attendance_records',
            field=models.ManyToManyField(related_name='performance_records', to='taskone.attendance'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='taskone.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='work_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
